# Generated by Django 4.2.4 on 2024-02-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("My_Todo_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="isDone",
            field=models.BooleanField(default=False),
        ),
    ]
